##########################################################
##### Hyprland desktop image
##########################################################
FROM ghcr.io/kingsleyzissou/hyprland-base:latest

##########################################################
##### Files
##########################################################
COPY files/desktop/ /

##########################################################
##### Desktop core
##########################################################
RUN dnf5 install -y \
  gtk3-devel \
  gtk4-devel \
  gtk-layer-shell-devel \
  gtk-murrine-engine \
  gobject-introspection-devel \
  libgtop2 \
  nautilus \
  qt5-qtgraphicaleffects \
  qt5-qtquickcontrols2 \
  qt5-qtsvg \
  qt6-qtquickcontrols2 \
  qt6-qtsvg

##########################################################
##### Hyprland
##########################################################
RUN dnf5 -y copr enable solopasha/hyprland
RUN dnf5 -y copr enable craftidore/wayblueorg-hyprland
RUN dnf5 -y install \
  appmenu-glib-translator \
  astal-devel \
  astal-gjs-devel \
  astal-gtk4-devel \
  astal-io-devel \
  astal-libs-devel \
  egl-wayland \
  grimblast \
  hypridle \
  hyprland-git \
  hyprland-git-debuginfo \
  hyprland-qt-support \
  hyprland-qtutils \
  hyprlock \
  hyprpaper \
  hyprpicker \
  hyprshot \
  hyprsunset \
  hyprwayland-scanner \
  ImageMagick \
  wf-recorder \
  wayland-protocols-devel \
  xdg-desktop-portal-hyprland
RUN dnf5 -y copr disable solopasha/hyprland
RUN dnf5 -y copr disable craftidore/wayblueorg-hyprland

##########################################################
##### Display & Theming
##########################################################
RUN dnf5 -y copr enable heus-sueh/packages
RUN dnf5 install -y \
  ddccontrol \
  ddccontrol-gtk \
  ddcutil \
  kanshi \
  matugen
RUN dnf5 -y copr disable heus-sueh/packages

##########################################################
##### Fonts
##########################################################
RUN dnf5 install -y \
  dejavu-sans-fonts \
  dejavu-sans-mono-fonts \
  google-noto-emoji-fonts \
  google-noto-sans-fonts \
  google-noto-sans-symbols-fonts \
  google-noto-sans-symbols2-fonts \
  google-roboto-fonts \
  jetbrains-mono-fonts

##########################################################
##### Utilities
##########################################################
RUN dnf5 -y copr enable alternateved/cliphist
RUN dnf5 install -y \
  cliphist \
  heif-pixbuf-loader \
  imv \
  man \
  mpv \
  tailscale \
  swappy \
  system-config-printer \
  udiskie \
  vulkan-validation-layers \
  vulkan-tools \
  wev

RUN dnf5 -y copr disable alternateved/cliphist

###########################################################
###### Applications
###########################################################
RUN dnf5 -y copr enable sneexy/zen-browser
RUN dnf5 install -y \
  1password \
  1password-cli \
  chromium \
  zen-browser
RUN dnf5 -y copr disable sneexy/zen-browser
RUN dnf5 config-manager setopt 1password.enabled=0

##########################################################
##### VPN
##########################################################
RUN mkdir -p /tmp/netbird && dnf5 download -y \
  --destdir=/tmp/netbird \
  netbird.x86_64 \
  netbird-ui
RUN rpm -i --nopost /tmp/netbird/*rpm && rm -rf /tmp/netbird
RUN dnf5 config-manager setopt Netbird.enabled=0

##########################################################
##### Clean
##########################################################
RUN dnf5 clean all

###########################################################
###### Flathub
###########################################################
RUN flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

##########################################################
##### Secrets
##########################################################
RUN mkdir -p /etc/secrets
RUN --mount=type=secret,id=container_auth cp /run/secrets/container_auth /usr/lib/container-auth.json
RUN chmod 0600 /usr/lib/container-auth.json
RUN ln -sr /usr/lib/container-auth.json /etc/ostree/auth.json

##########################################################
##### Services
##########################################################
RUN systemctl enable podman.socket
RUN systemctl enable tailscaled.service

LABEL summary="Hyprland desktop for bootable containers"
LABEL description="Hyprland compositor with theming, applications, and desktop utilities"
