##########################################################
##### Base image
##########################################################
FROM quay.io/fedora/fedora-bootc:44

RUN dnf5 -y update && dnf5 -y upgrade

##########################################################
##### Core
##########################################################
RUN dnf5 install -y \
  dnf5-plugins \
  flatpak \
  greetd \
  iwd \
  krb5-workstation \
  pciutils \
  pinentry-gnome3 \
  plymouth \
  terminus-fonts-console \
  tuigreet

##########################################################
##### Firmware
##########################################################
RUN dnf5 install -y \
  alsa-firmware \
  alsa-sof-firmware \
  alsa-tools-firmware \
  iwlwifi-dvm-firmware \
  iwlwifi-mvm-firmware

##########################################################
##### QEMU
##########################################################
RUN dnf5 install -y qemu qemu-kvm virt-install

##########################################################
##### Connectivity
##########################################################
RUN dnf5 group install -y networkmanager-submodules
RUN dnf5 install -y \
  bolt \
  blueman \
  firewall-config \
  network-manager-applet

##########################################################
##### Audio
##########################################################
RUN dnf5 install -y \
  alsa-plugins-oss \
  alsa-topology \
  alsa-utils \
  alsa-tools \
  inxi \
  pavucontrol \
  pamixer \
  pulseaudio-utils \
  mediainfo

##########################################################
##### Clean
##########################################################
RUN dnf5 clean all

##########################################################
##### re-configure initramfs
##########################################################
RUN set -x; kver=$(cd /usr/lib/modules && echo *); dracut -vf /usr/lib/modules/$kver/initramfs.img $kver

##########################################################
##### Services
##########################################################
RUN systemctl enable NetworkManager.service
RUN systemctl enable greetd.service

##########################################################
##### Mask
##########################################################
RUN systemctl mask rpm-ostree-countme.timer
RUN systemctl mask rpm-ostree-countme.service

LABEL summary="Base image with firmware for bootc desktop "
LABEL description="Fedora bootable container with firmware, networking, audio, and core system services"
