#!/bin/bash

MONITORS=$(xrandr | grep -w connected)

# external monitor should be either one of
# DP-1 or DP-3
if [[ $(echo $MONITORS | grep -c DP-1) -eq 1 ]]; then
  xrandr --output DP-1 --primary --auto
  xrandr --output eDP-1 --off
  exit 0
fi

if [[ $(echo $MONITORS | grep -c DP-3) -eq 1 ]]; then
  xrandr --output DP-3 --primary --auto
  xrandr --output eDP-1 --off
  exit 0
fi
