name: Build Image
on: [ pull_request ]

env:
  REGISTRY_USER: kingsleyzissou
  IMAGE_REGISTRY: ghcr.io/kingsleyzissou
  IMAGE: hyprland

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.AUTH_TOKEN }}

    - name: Build Modules Image
      id: build-modules
      uses: redhat-actions/buildah-build@v2
      with:
        image: ddcci
        tags: latest
        build-args: KERNEL=6.13.7-200.fc41.x86_64
        containerfiles: |
          ./files/modules/ddcci/Containerfile

    - name: Build Image
      id: build-image
      run: |
        podman build \
        --build-arg KERNEL=6.13.7-200.fc41.x86_64 \
        --secret id=container_auth,src=/run/user/1001/containers/auth.json \
        --tag ${{ env.IMAGE }} .
