name: Build and Push Image
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 0' # weekly Sunday 4am UTC
  workflow_dispatch:

env:
  REGISTRY_USER: kingsleyzissou
  IMAGE_REGISTRY: ghcr.io/kingsleyzissou

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-22.04
    outputs:
      base: ${{ steps.filter.outputs.base }}
      desktop: ${{ steps.filter.outputs.desktop }}
    steps:
    - uses: actions/checkout@v4

    - uses: dorny/paths-filter@v3
      id: filter
      if: github.event_name == 'push'
      with:
        filters: |
          base:
            - 'Containerfile.base'
            - 'files/system/**'
          desktop:
            - 'Containerfile'
            - 'files/repos/**'

  build-base:
    name: Build and push base image
    needs: changes
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      needs.changes.outputs.base == 'true'
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.AUTH_TOKEN }}

    - name: Build Base Image
      run: |
        podman build \
        --tag ${{ env.IMAGE_REGISTRY }}/hyprland-base:latest \
        --file Containerfile.base .

    - name: Push base image
      uses: redhat-actions/push-to-registry@v2
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        image: hyprland-base
        tags: latest

  build-desktop:
    name: Build and push desktop image
    needs: [changes, build-base]
    if: |
      always() &&
      !cancelled() &&
      !contains(needs.*.result, 'failure') &&
      (github.event_name == 'schedule' ||
       github.event_name == 'workflow_dispatch' ||
       needs.changes.outputs.base == 'true' ||
       needs.changes.outputs.desktop == 'true')
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.AUTH_TOKEN }}

    - name: Build Desktop Image
      run: |
        podman build \
        --tag ${{ env.IMAGE_REGISTRY }}/hyprland:latest \
        --file Containerfile .

    - name: Push desktop image
      uses: redhat-actions/push-to-registry@v2
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        image: hyprland
        tags: latest

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"
